### ISSUE TITLE
[BUG] Detector Azure MySQL memory usage , crit and major are reversed , crit unable to trigger

### ISSUE THREAD

**Issue by aogereau** [claranet/terraform-signalfx-detectors#478]
**What is the module?**
[integration_azure-flexible-mysql](https://github.com/claranet/terraform-signalfx-detectors/tree/master/modules/integration_azure-flexible-mysql)
[integration_azure-mysql](https://github.com/claranet/terraform-signalfx-detectors/tree/master/modules/integration_azure-mysql)

**What is the detector?**
Azure MySQL memory usage (for both)

**Describe the bug**
Crit and Major are reversed on signal FX for this detector for modules integration_azure-flexible-mysql and integration_azure-mysql . Crit is unable to trigger

**To Reproduce**
Here is how the triggers are defined in signalFX (see first screenshot)
```
detect(when(signal > 80, lasting='15m', at_least=1)).publish('MAJOR')
detect(when(signal > 90, lasting='15m', at_least=1) and (not when(signal > 80, lasting='15m', at_least=1))).publish('CRIT')
```

As it is defined, the Major will always be triggered when over the major threshold (default 80%). Crit would be triggered when over the critical threshold (by default 90%), but must not be over the major threshold at the same time
As the major threshold is inferior to the critical thresold, it will never be able to be triggered. Major will also stay on above critical threshold

**Expected behavior**

here is how it should be defined in signal FX

```
detect(when(signal > 90, lasting='15m', at_least=1)).publish('CRIT')
detect(when(signal > 80, lasting='15m', at_least=1) and (not when(signal > 90, lasting='15m', at_least=1))).publish('MAJOR')
```
Major will be triggered between major and critical threshods. Crit will be triggered over Critical threshold

**Additional context**
After modifying the detectors in signalfx terraform repos ( commit : https://github.com/claranet/terraform-signalfx-detectors/commit/0e45938eecc9bff4c338c8182ae7fc5560802790 ) and then taking into account the branch fix_azure_mysql_memory (second screenshot  ) a terraform plan gives the expected result (see last screenshot)

**Screenshots**
![image](https://github.com/claranet/terraform-signalfx-detectors/assets/138576425/32f144c0-617e-4b67-8f6e-6c36c2c06648)

![image](https://github.com/claranet/terraform-signalfx-detectors/assets/138576425/79caceb2-0ea8-4d19-8c1f-b50a64e12b55)

![image](https://github.com/claranet/terraform-signalfx-detectors/assets/138576425/3f40eb6f-5dc8-49ee-a3bf-f6c18515cd46)

**Comment by Shr3ps** [comment]
Can you specify which version of detectors module you're using?

This should be fixed with v1.22: https://github.com/claranet/terraform-signalfx-detectors/releases/tag/v1.22.0

**Comment by aogereau** [comment]
I was using 1.22 already. Problem is still present in master release

**Comment by Shr3ps** [comment]
Oh you're right, it's fixed for CPU for example, but not Memory.
